import { DeltaData, Scenario } from '../types';

// Delta files are bundled as JSON assets (generated by scripts/precompute_cmip6_delta.py)
// eslint-disable-next-line @typescript-eslint/no-var-requires
const DELTA_SSP245: DeltaData = require('../../assets/data/delta_ssp245.json');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const DELTA_SSP585: DeltaData = require('../../assets/data/delta_ssp585.json');

function getDeltaData(scenario: Scenario): DeltaData {
  return scenario === 'ssp245' ? DELTA_SSP245 : DELTA_SSP585;
}

/**
 * Bilinear interpolation of the CMIP6 delta grid to an exact lat/lon point.
 * Falls back to nearest-neighbour if the point is at a grid boundary.
 */
export function getDeltaForLocation(
  latitude: number,
  longitude: number,
  scenario: Scenario
): number {
  const data = getDeltaData(scenario);
  const { lats, lons, delta, resolution } = data;

  // Placeholder file not yet replaced — return a plausible default
  if (!delta) return scenario === 'ssp245' ? 1.5 : 2.5;

  // Clamp to grid bounds
  const lat = Math.max(lats[lats.length - 1], Math.min(lats[0], latitude));
  const lon = Math.max(lons[0],               Math.min(lons[lons.length - 1], longitude));

  // Find surrounding grid indices
  const latIdx = findIndex(lats, lat, true);   // lats are descending
  const lonIdx = findIndex(lons, lon, false);

  const i0 = Math.min(latIdx, lats.length - 2);
  const j0 = Math.min(lonIdx, lons.length - 2);
  const i1 = i0 + 1;
  const j1 = j0 + 1;

  // Bilinear weights
  const wLat = (lats[i0] - lat) / resolution;   // 0→1 as lat moves from i0→i1
  const wLon = (lon - lons[j0]) / resolution;   // 0→1 as lon moves from j0→j1

  const v00 = delta[i0]?.[j0] ?? 0;  // null = polar grid edge → treat as 0
  const v01 = delta[i0]?.[j1] ?? 0;
  const v10 = delta[i1]?.[j0] ?? 0;
  const v11 = delta[i1]?.[j1] ?? 0;

  const interpolated =
    v00 * (1 - wLat) * (1 - wLon) +
    v01 * (1 - wLat) *      wLon  +
    v10 *      wLat  * (1 - wLon) +
    v11 *      wLat  *      wLon;

  return parseFloat(interpolated.toFixed(1));
}

/** Convenience: return deltas for both scenarios at once (needed by chart view). */
export function getBothDeltas(
  latitude: number,
  longitude: number
): { ssp245: number; ssp585: number } {
  return {
    ssp245: getDeltaForLocation(latitude, longitude, 'ssp245'),
    ssp585: getDeltaForLocation(latitude, longitude, 'ssp585'),
  };
}

/** Find the index of the last element ≥ value (descending) or ≤ value (ascending). */
function findIndex(arr: number[], value: number, descending: boolean): number {
  if (descending) {
    for (let i = 0; i < arr.length - 1; i++) {
      if (arr[i] >= value && arr[i + 1] <= value) return i;
    }
  } else {
    for (let i = 0; i < arr.length - 1; i++) {
      if (arr[i] <= value && arr[i + 1] >= value) return i;
    }
  }
  return 0;
}
